version: '3'
services:
  fcm-python:
    image: fcm-python
    build:
      context: fcm-python
      dockerfile: Dockerfile
  starwars-api-people:
    image: fcmvictorgf87/starwars-api-people # Image names must be username/imagename(:tag) because username is mandatory if you want to push to Hub. Only big companies/projects can use an image name without username
    build: starwars-api-people # Shorthand when dockerfile is named Dockerfile
    pull_policy: if_not_present
  starwars-api-planets:
    image: fcmvictorgf87/starwars-api-planets # Image names must be username/imagename(:tag) because username is mandatory if you want to push to Hub. Only big companies/projects can use an image name without username
    build: starwars-api-planets # Shorthand when dockerfile is named Dockerfile
    pull_policy: if_not_present

  # fcm-python-big:
  #  image: fcm-python-big
  #  build:
  #    context: python-image
  #    dockerfile: Dockerfile.big