apiVersion: v1
kind: PersistentVolume
metadata:
  name: infinite-loop-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/victorgonzalez/projects/docker-talk/volumenillos/infinite-loop"